import type { Metadata } from "next";
import "./_styles/global.css";
import Logo from "./_components/Logo";

export const metadata: Metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Logo />
        {children}
      </body>
    </html>
  );
}
